executors:
  node12:
    docker:
      - image: circleci/node:latest
    working_directory: ~/repo

version: 2.1

jobs:
  build:
    executor: node12
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run: yarn

      - save_cache:
          paths:
            - node_modules
            - yarn.lock
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn test
      - run: yarn lint:ci
